var N = null;var sourcesIndex = {};
sourcesIndex["wayland_client"] = {"name":"","dirs":[{"name":"native_lib","files":["display.rs","event_queue.rs","mod.rs","proxy.rs"]}],"files":["display.rs","event_queue.rs","globals.rs","lib.rs","proxy.rs"]};
sourcesIndex["wayland_commons"] = {"name":"","files":["debug.rs","filter.rs","lib.rs","map.rs","socket.rs","user_data.rs","wire.rs"]};
sourcesIndex["wayland_cursor"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wayland_egl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wayland_protocols"] = {"name":"","files":["lib.rs","misc.rs","protocol_macro.rs","stable.rs","unstable.rs","wlr.rs"]};
sourcesIndex["wayland_scanner"] = {"name":"","files":["c_code_gen.rs","c_interface_gen.rs","common_gen.rs","lib.rs","parse.rs","protocol.rs","side.rs","util.rs"]};
sourcesIndex["wayland_server"] = {"name":"","dirs":[{"name":"native_lib","files":["client.rs","display.rs","globals.rs","mod.rs","resource.rs"]}],"files":["client.rs","display.rs","globals.rs","lib.rs","resource.rs"]};
sourcesIndex["wayland_sys"] = {"name":"","files":["client.rs","common.rs","cursor.rs","egl.rs","lib.rs","server.rs"]};
createSourceSidebar();
